CREATE TABLE  "CITIZENS"
   (	"CITIZEN_ID" NUMBER,
	"CNIC" VARCHAR2(15) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"DOB" DATE NOT NULL ENABLE,
	"GENDER" CHAR(1),
	"ADDRESS" VARCHAR2(255),
	"PHONE" VARCHAR2(15),
	"STATUS" VARCHAR2(20) DEFAULT 'active',
	 CHECK (gender IN ('M', 'F')) ENABLE,
	 PRIMARY KEY ("CITIZEN_ID") ENABLE,
	 UNIQUE ("CNIC") ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "TRG_CITIZENS_PK"
BEFORE INSERT ON citizens
FOR EACH ROW
BEGIN
    SELECT citizen_seq.NEXTVAL INTO :NEW.citizen_id FROM DUAL;
END;

/
ALTER TRIGGER  "TRG_CITIZENS_PK" ENABLE
/




-----------------Users table----------------------
CREATE TABLE  "USERS"
   (	"USER_ID" NUMBER,
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(255) NOT NULL ENABLE,
	"ROLE" VARCHAR2(20) NOT NULL ENABLE,
	 CHECK (role IN ('admin', 'officer')) ENABLE,
	 PRIMARY KEY ("USER_ID") ENABLE,
	 UNIQUE ("USERNAME") ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "TRG_USERS_PK"
BEFORE INSERT ON users
FOR EACH ROW
BEGIN
    SELECT user_seq.NEXTVAL INTO :NEW.user_id FROM DUAL;
END;

/
ALTER TRIGGER  "TRG_USERS_PK" ENABLE
/
